//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Affix> Affix { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Friend> Friend { get; set; }
        public virtual DbSet<GroupChat> GroupChat { get; set; }
        public virtual DbSet<GroupFriend> GroupFriend { get; set; }
        public virtual DbSet<Info> Info { get; set; }
        public virtual DbSet<Sms> Sms { get; set; }
        public virtual DbSet<WA_MFORENSICS_010100> WA_MFORENSICS_010100 { get; set; }
        public virtual DbSet<WA_MFORENSICS_010200> WA_MFORENSICS_010200 { get; set; }
        public virtual DbSet<WA_MFORENSICS_010202> WA_MFORENSICS_010202 { get; set; }
        public virtual DbSet<WA_MFORENSICS_010300> WA_MFORENSICS_010300 { get; set; }
        public virtual DbSet<WA_MFORENSICS_010400> WA_MFORENSICS_010400 { get; set; }
        public virtual DbSet<WA_MFORENSICS_010500> WA_MFORENSICS_010500 { get; set; }
        public virtual DbSet<WA_MFORENSICS_010700> WA_MFORENSICS_010700 { get; set; }
        public virtual DbSet<WA_MFORENSICS_020100> WA_MFORENSICS_020100 { get; set; }
        public virtual DbSet<WA_MFORENSICS_020200> WA_MFORENSICS_020200 { get; set; }
        public virtual DbSet<WA_MFORENSICS_020300> WA_MFORENSICS_020300 { get; set; }
        public virtual DbSet<WA_MFORENSICS_020400> WA_MFORENSICS_020400 { get; set; }
        public virtual DbSet<WA_MFORENSICS_020500> WA_MFORENSICS_020500 { get; set; }
        public virtual DbSet<WA_MFORENSICS_020600> WA_MFORENSICS_020600 { get; set; }
        public virtual DbSet<WA_MFORENSICS_020700> WA_MFORENSICS_020700 { get; set; }
        public virtual DbSet<WA_MFORENSICS_090400> WA_MFORENSICS_090400 { get; set; }
        public virtual DbSet<Zone> Zone { get; set; }
    }
}
