//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupChat
    {
        public string ID { get; set; }
        public string TargetID { get; set; }
        public string AccountType { get; set; }
        public string Account { get; set; }
        public string GroupNum { get; set; }
        public string GroupName { get; set; }
        public string FriendAccount { get; set; }
        public string FriendNickName { get; set; }
        public string Content { get; set; }
        public string SendTime { get; set; }
        public string Direction { get; set; }
        public string DeleteStatus { get; set; }
        public Nullable<long> Count { get; set; }
        public string IsDeleted { get; set; }
        public string Affix { get; set; }
    }
}
