//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_MFORENSICS_010700
    {
        public string ID { get; set; }
        public string COLLECT_TARGET_ID { get; set; }
        public string MSISDN { get; set; }
        public string RELATIONSHIP_ACCOUNT { get; set; }
        public string RELATIONSHIP_NAME { get; set; }
        public string LOCAL_ACTION { get; set; }
        public string MAIL_SEND_TIME { get; set; }
        public string CONTENT { get; set; }
        public string MAIL_VIEW_STATUS { get; set; }
        public string MAIL_SAVE_FOLDER { get; set; }
        public string PRIVACYCONFIG { get; set; }
        public string DELETE_STATUS { get; set; }
        public string DELETE_TIME { get; set; }
        public string INTERCEPT_STATE { get; set; }
    }
}
