//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_MFORENSICS_010100
    {
        public string ID { get; set; }
        public string COLLECT_TARGET_ID { get; set; }
        public string MANUFACTURER { get; set; }
        public string NAME { get; set; }
        public string CERTIFICATE_TYPE { get; set; }
        public string CERTIFICATE_CODE { get; set; }
        public string CAPTURE_TIME { get; set; }
        public string PRINCIPAL_NAME { get; set; }
        public string POLICE_NO { get; set; }
        public string INCHARGE_WA_DEPARTMENT { get; set; }
        public string CASE_NO { get; set; }
        public string CASE_TYPE { get; set; }
        public string CASE_NAME { get; set; }
        public string SEXCODE { get; set; }
        public string NATION { get; set; }
        public string BIRTHDAY { get; set; }
        public string REGISTERED_ADDRESS { get; set; }
        public string CERT_ISSUE_UNIT { get; set; }
        public string CERT_EEFFECT_DATE { get; set; }
        public string CERT_INVALID_DATE { get; set; }
        public string USER_PHOTO { get; set; }
        public string MATERIALS_NAME { get; set; }
        public string MODEL { get; set; }
        public string VERSION { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string MATERIALS_SERIAL { get; set; }
        public string IP_ADDRESS { get; set; }
        public string DUAL_TIME { get; set; }
        public string GA_CASE_NO { get; set; }
        public string GA_CASE_TYPE { get; set; }
        public string GA_CASE_NAME { get; set; }
        public string REMARK { get; set; }
        public string MIME_NAME { get; set; }
        public string MAINFILE { get; set; }
        public string FINGER_PRINT_VALUE { get; set; }
    }
}
