//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_MFORENSICS_020700
    {
        public string ID { get; set; }
        public string COLLECT_TARGET_ID { get; set; }
        public string CONTACT_ACCOUNT_TYPE { get; set; }
        public string ACCOUNT_ID { get; set; }
        public string ACCOUNT { get; set; }
        public string FRIEND_ID { get; set; }
        public string FRIEND_ACCOUNT { get; set; }
        public string FRIEND_NICKNAME { get; set; }
        public string WEIBO_MESSAGE_TYPE { get; set; }
        public string MAIL_SEND_TIME { get; set; }
        public string WEIBO_MESSAGE { get; set; }
        public string WEIBO_REPLY_COUNTER { get; set; }
        public string WEIBO_RETWEET_COUNTER { get; set; }
        public string WEIBO_LIKE_COUNTER { get; set; }
        public string MBLOG_ID { get; set; }
        public string RELEVANT_MBLOG_ID { get; set; }
        public string IDROOT_MBLOG_ID { get; set; }
        public string GROUP_NUM { get; set; }
        public string DELETE_STATUS { get; set; }
        public string DELETE_TIME { get; set; }
        public string MAINFILE { get; set; }
        public string MEDIA_TYPE { get; set; }
        public string CITY_CODE { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public string ABOVE_SEALEVEL { get; set; }
        public string FANS_COUNTER { get; set; }
        public string VISITS { get; set; }
        public string DUAL_TIME { get; set; }
    }
}
