//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_MFORENSICS_020100
    {
        public string ID { get; set; }
        public string COLLECT_TARGET_ID { get; set; }
        public string CONTACT_ACCOUNT_TYPE { get; set; }
        public string ACCOUNT_ID { get; set; }
        public string ACCOUNT { get; set; }
        public string REGIS_NICKNAME { get; set; }
        public string PASSWORD { get; set; }
        public string INSTALL_TIME { get; set; }
        public string AREA { get; set; }
        public string CITY_CODE { get; set; }
        public string FIXED_PHONE { get; set; }
        public string MSISDN { get; set; }
        public string EMAIL_ACCOUNT { get; set; }
        public string CERTIFICATE_TYPE { get; set; }
        public string CERTIFICATE_CODE { get; set; }
        public string SEXCODE { get; set; }
        public string AGE { get; set; }
        public string POSTAL_ADDRESS { get; set; }
        public string POSTAL_CODE { get; set; }
        public string OCCUPATION_NAME { get; set; }
        public string BLOOD_TYPE { get; set; }
        public string NAME { get; set; }
        public string SIGN_NAME { get; set; }
        public string PERSONAL_DESC { get; set; }
        public string REG_CITY { get; set; }
        public string GRADUATESCHOOL { get; set; }
        public string ZODIAC { get; set; }
        public string CONSTALLATION { get; set; }
        public string BIRTHDAY { get; set; }
        public string DELETE_STATUS { get; set; }
        public string DELETE_TIME { get; set; }
        public string HASH_TYPE { get; set; }
        public string USER_PHOTO { get; set; }
        public string ACCOUNT_REG_DATE { get; set; }
        public string LAST_LOGIN_TIME { get; set; }
        public string LATEST_MOD_TIME { get; set; }
    }
}
