//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_MFORENSICS_010202
    {
        public string ID { get; set; }
        public string COLLECT_TARGET_ID { get; set; }
        public string OS_TYPE { get; set; }
        public string OS_NAME { get; set; }
        public string INSTALLL_TIME { get; set; }
        public string TIMEZONE { get; set; }
        public string CRACK_STATUS { get; set; }
    }
}
