//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_MFORENSICS_020300
    {
        public string ID { get; set; }
        public string COLLECT_TARGET_ID { get; set; }
        public string CONTACT_ACCOUNT_TYPE { get; set; }
        public string ACCOUNT_ID { get; set; }
        public string ACCOUNT { get; set; }
        public string GROUP_NUM { get; set; }
        public string GROUP_NAME { get; set; }
        public string FRIEND_ID { get; set; }
        public string FRIEND_ACCOUNT { get; set; }
        public string GROUP_OWNER_NICKNAME { get; set; }
        public string GROUP_MEMBER_COUNT { get; set; }
        public string GROUP_MAX_MEMBER_COUT { get; set; }
        public string GROUP_NOTICE { get; set; }
        public string GROUP_DESCRIPTION { get; set; }
        public string DELETE_STATUS { get; set; }
        public string DELETE_TIME { get; set; }
        public string GROUP_OWNER_INTERNAL_ID { get; set; }
        public string GROUP_OWNER { get; set; }
        public string GROUP_ADMIN_NICKNAME { get; set; }
        public string CREATE_TIME { get; set; }
        public string GROUPPHOTO { get; set; }
    }
}
