//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_MFORENSICS_090400
    {
        public string ID { get; set; }
        public string COLLECT_TARGET_ID { get; set; }
        public string MEDIA_TYPE { get; set; }
        public string MIME_ORIGINAL_NAME { get; set; }
        public string LOCATE_TYPE { get; set; }
        public string LOGIN_TIME { get; set; }
        public string CITY_CODE { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public string DELETE_STATUS { get; set; }
        public string DELETE_TIME { get; set; }
    }
}
